### ISSUE TITLE
unable to configure under fedora21

### ISSUE THREAD

**Issue by regnirpsj** [matus-chochlik/oglplus#100]
hi matus,
any attempt to configure a head-branch checkout fails under f21 (recently upgraded) by saying that the opengl version could not be detected. what do i have to do to find/provide information what's the problem?

**Comment by matus-chochlik** [comment]
Hi,

try re-running configure with `--debug-config` and `--debug-gl-ver-error`. When the detection fails go to the subdirectory of `_build/gl/` where the makefiles were generated and try to run `make`, if the test executable builds successfully try running it. This should give you an idea what went wrong.

**Comment by regnirpsj** [comment]
thanks. the problem seems to be the system install. configuring w/ clang works, so i have to find out what went wrong during system upgrade.
