### ISSUE TITLE
config not finding opengl version

### ISSUE THREAD

**Issue by normvcr** [matus-chochlik/oglplus#106]
I got this error both with version 0.59 and today's git checkout:
-- Using GLX for GL context initialization.
-- Using native OpenGL API library
-- Detecting OpenGL version
Could not detect GL version, assuming 3.0

(my actual version is 4.4)
This is my command line
../configure.sh --no-docs  --library-dir=/usr/lib64/nvidia --include-dir=/usr/include/nvidia 

Am running on fedora 20, x86-64
Thank you!

**Comment by normvcr** [comment]
As a follow up, I have been able to work around the problem, and have installed OGLplus. I set a few variables in CMakeLists.txt, but the gcc linker was still not finding -lGL .  I was not able get -L/usr/lib64/nvidia to percolate down to the link lines.  So I soft-linked: 
            ln -s /usr/lib64/nvidia/libGL.so  /usr/lib64/libGL.so
Also, my installed GL Math packag, glm, did not have the vec2.hpp header, so I installed glm manually from the glm web site, and then the OGLplus installation completed.
I look forward to using this package, and will be happy to work together to smooth out the installation process.  Thank you!

**Comment by matus-chochlik** [comment]
Hi,

sorry for the late response. I'm glad to see that You got it going. I usually create a simple script on my Linux machines which does `export LD_LIBRARY_PATH="/usr/lib/nvidia-whatever:${LD_LIBRARY_PATH}"` before running configure or the tests.

BR

Matus
