### ISSUE TITLE
oglplus::Program::BuildInclude && clang 3.5

### ISSUE THREAD

**Issue by regnirpsj** [matus-chochlik/oglplus#113]
on fedora21 clang 3.5 chokes on this while gcc 4.9.2 is perfectly happy (as well as vs2013); `b` and `d` are of type `std::string`.

```
> error: no matching member function for call to 'BuildInclude'
        prg_.MakeSeparable(true).BuildInclude({ b, d, }).Link().Use();
        ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
> note: candidate function not viable: cannot convert initializer list argument to 'oglplus::GLSLString'
        ObjectOps& BuildInclude(GLSLString&& incl)
                   ^
> note: candidate function not viable: cannot convert initializer list argument to 'oglplus::GLSLStrings'
        ObjectOps& BuildInclude(GLSLStrings&& incl)
                   ^
> note: candidate function not viable: cannot convert initializer list argument to 'const oglplus::GLSLSource'
        ObjectOps& BuildInclude(const GLSLSource&& incl)
                   ^
```

this is with a recent clone of the `develop` as well as the `master` branch.

**Comment by matus-chochlik** [comment]
This looks like a problem with the Boost.Config library, which for clang defines the ``BOOST_NO_INITIALIZER_LISTS`` preprocessor symbol even if initializer lists are supported. OGLplus picks this up, and disables the constructors with initializer lists.

At the moment You can fix this by defining ``OGLPLUS_NO_INITIALIZER_LISTS 0`` before including the oglplus headers.

**Comment by matus-chochlik** [comment]
I did some changes to the build system and now it is possible to disable the use of the Boost.Config library (if it was detected) either by defining ``OGLPLUS_USE_BOOST_CONFIG 0`` before including oglplus, or by specifying the ``--no-boost-config`` option to the configuration script.

HTH

**Comment by regnirpsj** [comment]
thanks, i'll try both later today.
