### ISSUE TITLE
Trying to build a project using oglplus

### ISSUE THREAD

**Issue by Nesh108** [matus-chochlik/oglplus#114]
Hello there!

I am trying to get this example work: https://github.com/OculusRiftInAction/OculusRiftInAction/blob/master/examples/cpp/opencv/Example_13_2_SimpleWebcamDemo.cpp 

And I am getting this error:

```oglplus/include/oglplus/prog_var/set_ops.hpp:273:10: error: ‘base_location’ was not declared in this scope```

I tried to comment out that line (```Index(base_location)```) but more errors spawn:

```oglplus/include/oglplus/error/basic.hpp:420:13: error: expected unqualified-id before ‘.’ token```

I tried using the latest version of oglplus (both master and devel) but I am having the same problems. 

Note: I couldn't make the project but I think I don't need to do that as I only need the includes.

**Comment by matus-chochlik** [comment]
Hi, it should be fixed on ``develop`` now. It works with g++ and clang++, but I could not test it yet with msvc.

**Comment by Nesh108** [comment]
This is truly amazing! Such a speed!

Thanks a lot, Matus!
