### ISSUE TITLE
Error building project on OSX from bad reference to non-existent identifier 'size'

### ISSUE THREAD

**Issue by jherico** [matus-chochlik/oglplus#115]
I'm building a project and using this for my include code:

```

#define OGLPLUS_USE_GLCOREARB_H 0
#if defined(__APPLE__)
#define OGLPLUS_USE_GL3_H 1
#elif defined(WIN32)
#define OGLPLUS_USE_GLEW 1
#pragma warning(disable : 4068)
#elif defined(ANDROID)
#else
#define OGLPLUS_USE_GLCOREARB_H 1
#endif

#define OGLPLUS_USE_BOOST_CONFIG 1
#define OGLPLUS_NO_SITE_CONFIG 1
#define OGLPLUS_LOW_PROFILE 1
#include <oglplus/gl.hpp>
#include <oglplus/all.hpp>
#include <oglplus/interop/glm.hpp>
#include <oglplus/bound/texture.hpp>
#include <oglplus/bound/framebuffer.hpp>
#include <oglplus/bound/renderbuffer.hpp>
#include <oglplus/shapes/wrapper.hpp>
#include <oglplus/shapes/plane.hpp>
```

The problem arises in texture.ipp where there are a couple of references to 
`OGLPLUS_FAKE_USE(size);` but there is no `size` value in scope.  

Commenting out the two instances seems to resolve the issue.

**Comment by matus-chochlik** [comment]
Hi,

Should be fixed on develop, but beware that I did some changes recently on develop which were not yet thoroughly tested.

**Comment by matus-chochlik** [comment]
OK, I've did some testing of the develop branch with clang and gcc and it should be ready to be used. I plan a to do a few more changes and then do a release (hopefully by the end of the week)
